<Project Sdk="Microsoft.NET.Sdk">

  <!-- Targets -->
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net7.0</TargetFrameworks>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <!-- Build -->
  <PropertyGroup>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <!-- Package info -->
  <PropertyGroup>
    <Description>Lightweight and simple TCP client-server .NET library with RMI support.</Description>
    <PackageTags>tcp; ip; sockets; networking; server; client; client-server; rmi</PackageTags>
    <PackageProjectUrl>https://www.tagbites.com/net</PackageProjectUrl>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
  </PropertyGroup>

  <!-- References -->
  <ItemGroup>
    <PackageReference Include="System.Reflection.DispatchProxy" Version="4.3.0" Condition="'$(TargetFramework)' == 'netstandard2.0'" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
  </ItemGroup>

</Project>
